---
  env:
    browser: true
    node: true
    es6: true
  parserOptions:
    sourceType: module
  extends:
  - plugin:prettier/recommended
  rules:
    prettier/prettier:
    - error
    - singleQuote: true
      bracketSpacing: true
      trailingComma: es5
